### ISSUE TITLE
Can't insatll

### ISSUE THREAD

**Issue by PH9** [146BC/RomeBuild#14]
macOS HighSierra - 10.13.4 (17E199)

Homebrew 1.5.14
Homebrew/homebrew-core (git revision 9f8b6; last commit 2018-04-05)

```
$ brew install 146BC/repo/romebuild
==> Installing romebuild from 146bc/repo
==> Downloading https://github.com/146BC/RomeBuild/archive/0.4.0.tar.gz
Already downloaded: /Users/wasith/Library/Caches/Homebrew/romebuild-0.4.0.tar.gz
==> make install PREFIX=/usr/local/Cellar/romebuild/0.4.0
Last 15 lines from /Users/wasith/Library/Logs/Homebrew/romebuild/01.make:
install
PREFIX=/usr/local/Cellar/romebuild/0.4.0

carthage bootstrap --platform OSX
*** Checking out CommandLine at "2.2.2"
*** Checking out RomeKit at "0.3.0"
*** Checking out Alamofire at "3.5.1"
*** Checking out Progress.swift at "68662d3b3589d2a7b0221966ae3019f97201b44d"
*** Cloning Progress.swift
*** Cloning RomeKit
*** Cloning CommandLine
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/146BC/RomeKit.git /Users/wasith/Library/Caches/org.carthage.CarthageKit/dependencies/RomeKit) failed with exit code 1:
/Users/wasith/Library/Caches/org.carthage.CarthageKit/dependencies/RomeKit: Operation not permitted

make: *** [install] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/146bc/homebrew-repo/issues

/usr/local/Homebrew/Library/Homebrew/exceptions.rb:426:in `block in dump': undefined method `check_for_bad_install_name_tool' for #<Homebrew::Diagnostic::Checks:0x0000010219f610> (NoMethodError)
Did you mean?  check_for_tap_ruby_files_locations
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `each'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
```

**Comment by PH9** [comment]
after add github token for `HOMEBREW_GITHUB_API_TOKEN`

```
$ brew install 146BC/repo/romebuild
==> Installing romebuild from 146bc/repo
==> Downloading https://github.com/146BC/RomeBuild/archive/0.4.0.tar.gz
Already downloaded: /Users/wasith/Library/Caches/Homebrew/romebuild-0.4.0.tar.gz
==> make install PREFIX=/usr/local/Cellar/romebuild/0.4.0
Last 15 lines from /Users/wasith/Library/Logs/Homebrew/romebuild/01.make:
install
PREFIX=/usr/local/Cellar/romebuild/0.4.0

carthage bootstrap --platform OSX
*** Checking out CommandLine at "2.2.2"
*** Checking out RomeKit at "0.3.0"
*** Checking out Alamofire at "3.5.1"
*** Checking out Progress.swift at "68662d3b3589d2a7b0221966ae3019f97201b44d"
*** Cloning Progress.swift
*** Cloning RomeKit
*** Cloning CommandLine
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/146BC/RomeKit.git /Users/wasith/Library/Caches/org.carthage.CarthageKit/dependencies/RomeKit) failed with exit code 1:
/Users/wasith/Library/Caches/org.carthage.CarthageKit/dependencies/RomeKit: Operation not permitted

make: *** [install] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/146bc/homebrew-repo/issues

/usr/local/Homebrew/Library/Homebrew/exceptions.rb:426:in `block in dump': undefined method `check_for_bad_install_name_tool' for #<Homebrew::Diagnostic::Checks:0x0000010219f610> (NoMethodError)
Did you mean?  check_for_tap_ruby_files_locations
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `each'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:138:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:30:in `<main>'
```

**Comment by PH9** [comment]
sorry

```
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/146bc/homebrew-repo/issues
```
